"""Add description and creator_id to Roadmap

Revision ID: 2183b66ae724
Revises: 311e94e307eb
Create Date: 2026-02-09 10:07:08.228007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2183b66ae724'
down_revision = '311e94e307eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_roadmaps_creator_id_users', 'users', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.drop_constraint('fk_roadmaps_creator_id_users', type_='foreignkey')
        batch_op.drop_column('creator_id')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
