"""Add full_name and degree

Revision ID: 311e94e307eb
Revises: 
Create Date: 2026-02-09 10:00:52.998402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311e94e307eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('degree', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_info', schema=None) as batch_op:
        batch_op.drop_column('degree')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
